"""baseline: accounts, users, clinics, subscriptions, provisioning_events, audit_events

Revision ID: 91631e83a925
Revises: 
Create Date: 2026-09-08 09:34:54.601896
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models define custom column types (GUID, JSONColumn, EncryptedString)
# that autogenerated migrations reference by their module path.
import app.models


revision: str = '91631e83a925'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_slug'), ['slug'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('actor_user_id', app.models.GUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('account_id', app.models.GUID(), nullable=True),
    sa.Column('clinic_id', app.models.GUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', app.models.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)

    op.create_table('clinics',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('account_id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('booking_url', sa.String(length=500), nullable=True),
    sa.Column('review_url', sa.String(length=500), nullable=True),
    sa.Column('open_hour', sa.Integer(), nullable=False),
    sa.Column('close_hour', sa.Integer(), nullable=False),
    sa.Column('railway_project_id', sa.String(length=64), nullable=True),
    sa.Column('railway_environment_id', sa.String(length=64), nullable=True),
    sa.Column('railway_service_id', sa.String(length=64), nullable=True),
    sa.Column('railway_postgres_service_id', sa.String(length=64), nullable=True),
    sa.Column('railway_volume_id', sa.String(length=64), nullable=True),
    sa.Column('engine_url', sa.String(length=500), nullable=True),
    sa.Column('encryption_key', app.models.SealedString(), nullable=True),
    sa.Column('fingerprint_secret', app.models.SealedString(), nullable=True),
    sa.Column('internal_api_token', app.models.SealedString(), nullable=True),
    sa.Column('staff_api_token', app.models.SealedString(), nullable=True),
    sa.Column('vapi_webhook_secret', app.models.SealedString(), nullable=True),
    sa.Column('integrations', app.models.JSONColumn(), nullable=False),
    sa.Column('key_backup_confirmed', sa.Boolean(), nullable=False),
    sa.Column('provisioned_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_clinics_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinics_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_clinics_status'), ['status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('account_id', app.models.GUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=True),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('clinic_limit', sa.Integer(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_account_id'), ['account_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    op.create_table('users',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('account_id', app.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('session_epoch', sa.String(length=32), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_account_email', ['account_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reset_token_hash'), ['reset_token_hash'], unique=False)

    op.create_table('provisioning_events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('clinic_id', app.models.GUID(), nullable=False),
    sa.Column('step', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('details', app.models.JSONColumn(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provisioning_events', schema=None) as batch_op:
        batch_op.create_index('ix_provisioning_clinic_created', ['clinic_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provisioning_events_step'), ['step'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provisioning_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provisioning_events_step'))
        batch_op.drop_index(batch_op.f('ix_provisioning_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_provisioning_events_clinic_id'))
        batch_op.drop_index('ix_provisioning_clinic_created')

    op.drop_table('provisioning_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token_hash'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_account_id'))
        batch_op.drop_index('ix_users_account_email')

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_account_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_status'))
        batch_op.drop_index(batch_op.f('ix_clinics_slug'))
        batch_op.drop_index('ix_clinics_account_status')
        batch_op.drop_index(batch_op.f('ix_clinics_account_id'))

    op.drop_table('clinics')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index(batch_op.f('ix_audit_events_account_id'))
        batch_op.drop_index('ix_audit_action_created')
        batch_op.drop_index('ix_audit_account_created')

    op.drop_table('audit_events')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_slug'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
