"""clinic custom domain

Revision ID: aae39231e8fd
Revises: 91631e83a925
Create Date: 2026-09-08 11:17:38.816312
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models define custom column types (GUID, JSONColumn, EncryptedString)
# that autogenerated migrations reference by their module path.
import app.models


revision: str = 'aae39231e8fd'
down_revision: Union[str, None] = '91631e83a925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_domain', sa.String(length=253), nullable=True))
        batch_op.add_column(sa.Column('railway_custom_domain_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinics_custom_domain'), ['custom_domain'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_custom_domain'))
        batch_op.drop_column('railway_custom_domain_id')
        batch_op.drop_column('custom_domain')

    # ### end Alembic commands ###
