import "server-only";
import { createHash, createHmac, timingSafeEqual, randomUUID } from "node:crypto";
import { mkdir, writeFile, readFile, unlink } from "node:fs/promises";
import path from "node:path";

import { signRequest, uriEncode, amzDateNow } from "./s3";

/**
 * Private object storage for prescriptions and health records.
 *
 * Non-negotiables, enforced by this module rather than by convention:
 *
 *  - Nothing here ever returns a public URL. The only way to read an object is
 *    a signed, expiring URL minted server-side.
 *  - The storage key is opaque and unguessable (UUID), so knowing a customer's
 *    id tells you nothing about their prescription paths.
 *  - The signature covers the key *and* the expiry, so neither can be edited
 *    without invalidating it.
 *
 * A signed URL is necessary but not sufficient: the route that serves these
 * also re-checks that the caller is entitled to the record. A leaked URL alone
 * must not be enough.
 */

export type StoredObject = {
  body: Buffer;
  contentType: string;
};

export interface PrivateStorage {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

/** Where local development stores objects. Never inside /public. */
const LOCAL_ROOT = path.resolve(process.cwd(), ".private-storage");

class LocalDiskStorage implements PrivateStorage {
  readonly name = "local-disk";

  private resolve(key: string): string {
    // Keys are generated by this module, but a traversal check costs nothing
    // and this is the one place a bad key would escape the sandbox.
    const target = path.resolve(LOCAL_ROOT, key);
    if (!target.startsWith(LOCAL_ROOT + path.sep)) {
      throw new Error("Refusing to resolve a storage key outside the root.");
    }
    return target;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const target = this.resolve(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body);
    await writeFile(`${target}.meta`, contentType, "utf8");
  }

  async get(key: string): Promise<StoredObject | null> {
    try {
      const target = this.resolve(key);
      const [body, contentType] = await Promise.all([
        readFile(target),
        readFile(`${target}.meta`, "utf8").catch(() => "application/octet-stream"),
      ]);
      return { body, contentType };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      const target = this.resolve(key);
      await unlink(target);
      await unlink(`${target}.meta`).catch(() => {});
    } catch {
      // Already gone.
    }
  }
}

/**
 * S3-compatible private storage.
 *
 * Works against AWS S3, Cloudflare R2, DigitalOcean Spaces, MinIO and Backblaze
 * B2 — the signing is identical and the endpoint is configurable.
 *
 * Two properties this class is responsible for, both of which are the reason
 * prescriptions are not simply put on a CDN:
 *
 *  - It never constructs a public URL. `get` returns bytes, which the
 *    application streams through `/api/private-file` after re-authorising the
 *    caller. There is deliberately no `getPublicUrl` and no presigned-GET
 *    helper — a presigned S3 URL would bypass that re-authorisation.
 *  - Objects are written with private ACL and server-side encryption. A bucket
 *    misconfigured as public would still not make these readable without the
 *    key, and the key is a UUID that appears nowhere client-side.
 */
class S3Storage implements PrivateStorage {
  readonly name = "s3";

  constructor(
    private readonly config: {
      bucket: string;
      region: string;
      accessKeyId: string;
      secretAccessKey: string;
      /** Custom endpoint for non-AWS providers. */
      endpoint?: string;
    },
  ) {}

  /**
   * Path-style addressing (`/bucket/key`) rather than virtual-host style.
   *
   * Every S3-compatible provider supports path style; MinIO and several others
   * do not support virtual-host style without extra DNS setup. Buckets here are
   * named by an operator, not by end users, so the path-style bucket-naming
   * restrictions are not a constraint.
   */
  private target(key: string): { url: string; host: string; path: string } {
    const { bucket, region, endpoint } = this.config;
    const base = endpoint?.replace(/\/$/, "") ?? `https://s3.${region}.amazonaws.com`;
    const host = new URL(base).host;
    // The key is encoded segment-by-segment: slashes stay as separators, but
    // everything else is RFC 3986 encoded so the signature matches the path.
    const encodedKey = key.split("/").map((s) => uriEncode(s)).join("/");
    const path = `/${uriEncode(bucket)}/${encodedKey}`;
    return { url: `${base}${path}`, host, path };
  }

  private async request(
    method: "PUT" | "GET" | "DELETE",
    key: string,
    body?: Buffer,
    contentType?: string,
  ): Promise<Response> {
    const { url, host, path } = this.target(key);
    const amzDate = amzDateNow();
    const payloadHash = createHash("sha256")
      .update(body ?? Buffer.alloc(0))
      .digest("hex");

    const headers: Record<string, string> = {
      Host: host,
      "x-amz-date": amzDate,
      "x-amz-content-sha256": payloadHash,
    };
    if (body) {
      headers["Content-Type"] = contentType ?? "application/octet-stream";
      // Belt and braces alongside a private bucket policy. Providers that do
      // not implement ACLs ignore these; AWS honours them.
      headers["x-amz-acl"] = "private";
      headers["x-amz-server-side-encryption"] = "AES256";
    }

    headers.Authorization = signRequest({
      method,
      path,
      headers,
      payloadHash,
      region: this.config.region,
      service: "s3",
      accessKeyId: this.config.accessKeyId,
      secretAccessKey: this.config.secretAccessKey,
      amzDate,
    });

    return fetch(url, { method, headers, body: body ? new Uint8Array(body) : undefined });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const response = await this.request("PUT", key, body, contentType);
    if (!response.ok) {
      // The body carries S3's error code; without it a 403 is unattributable
      // between bad credentials, bad clock and bad bucket policy.
      throw new Error(
        `S3 PUT failed (${response.status}): ${(await response.text()).slice(0, 500)}`,
      );
    }
  }

  async get(key: string): Promise<StoredObject | null> {
    const response = await this.request("GET", key);
    if (response.status === 404) return null;
    if (!response.ok) {
      throw new Error(
        `S3 GET failed (${response.status}): ${(await response.text()).slice(0, 500)}`,
      );
    }
    return {
      body: Buffer.from(await response.arrayBuffer()),
      contentType: response.headers.get("content-type") ?? "application/octet-stream",
    };
  }

  async delete(key: string): Promise<void> {
    const response = await this.request("DELETE", key);
    // S3 returns 204 for a delete, and 204 for deleting something absent.
    if (!response.ok && response.status !== 404) {
      throw new Error(
        `S3 DELETE failed (${response.status}): ${(await response.text()).slice(0, 500)}`,
      );
    }
  }
}

let storage: PrivateStorage | null = null;

export function getStorage(): PrivateStorage {
  if (storage) return storage;

  const bucket = process.env.S3_BUCKET_PRESCRIPTIONS;
  if (bucket) {
    const accessKeyId = process.env.S3_ACCESS_KEY_ID;
    const secretAccessKey = process.env.S3_SECRET_ACCESS_KEY;
    const region = process.env.S3_REGION;

    // Fail here rather than on the first upload. A pharmacy that discovers its
    // storage is misconfigured when a customer tries to upload a prescription
    // has discovered it too late.
    const missing = [
      !accessKeyId && "S3_ACCESS_KEY_ID",
      !secretAccessKey && "S3_SECRET_ACCESS_KEY",
      !region && "S3_REGION",
    ].filter(Boolean);
    if (missing.length > 0) {
      throw new Error(
        `S3_BUCKET_PRESCRIPTIONS is set but ${missing.join(", ")} ${
          missing.length === 1 ? "is" : "are"
        } not. Private storage must be fully configured or not configured at all.`,
      );
    }

    storage = new S3Storage({
      bucket,
      region: region!,
      accessKeyId: accessKeyId!,
      secretAccessKey: secretAccessKey!,
      endpoint: process.env.S3_ENDPOINT || undefined,
    });
    return storage;
  }

  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "No private storage configured. Prescription images are sensitive " +
        "personal data and must not be written to the application filesystem " +
        "in production. Set S3_BUCKET_PRESCRIPTIONS.",
    );
  }

  storage = new LocalDiskStorage();
  return storage;
}

/** Opaque, unguessable key. Prefix is organisational only, never a permission. */
export function newPrescriptionKey(extension: string): string {
  const safeExt = extension.replace(/[^a-z0-9]/gi, "").slice(0, 5) || "bin";
  return `prescriptions/${randomUUID()}.${safeExt}`;
}

export function newHealthRecordKey(extension: string): string {
  const safeExt = extension.replace(/[^a-z0-9]/gi, "").slice(0, 5) || "bin";
  return `health-records/${randomUUID()}.${safeExt}`;
}

function signingSecret(): string {
  const secret = process.env.AUTH_SECRET;
  if (!secret) {
    throw new Error("AUTH_SECRET is required to sign private storage URLs.");
  }
  return secret;
}

function sign(key: string, expiresAt: number): string {
  return createHmac("sha256", signingSecret())
    .update(`${key}:${expiresAt}`)
    .digest("hex");
}

/**
 * Mints a short-lived signed URL.
 *
 * Callers must have already checked that the requester is entitled to the
 * object — this function does not know who is asking.
 */
export function signObjectUrl(key: string, ttlSeconds: number): string {
  const expiresAt = Math.floor(Date.now() / 1000) + ttlSeconds;
  const signature = sign(key, expiresAt);
  const params = new URLSearchParams({
    key,
    exp: String(expiresAt),
    sig: signature,
  });
  return `/api/private-file?${params.toString()}`;
}

export type VerifiedSignature =
  | { ok: true; key: string }
  | { ok: false; reason: "expired" | "invalid" };

export function verifyObjectUrl(
  key: string | null,
  exp: string | null,
  sig: string | null,
): VerifiedSignature {
  if (!key || !exp || !sig) return { ok: false, reason: "invalid" };

  const expiresAt = Number(exp);
  if (!Number.isFinite(expiresAt)) return { ok: false, reason: "invalid" };

  const expected = sign(key, expiresAt);
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(sig, "utf8");
  if (a.length !== b.length || !timingSafeEqual(a, b)) {
    return { ok: false, reason: "invalid" };
  }

  // Expiry is checked after the signature so an attacker cannot use response
  // timing to distinguish a forged signature from a merely stale one.
  if (expiresAt < Math.floor(Date.now() / 1000)) {
    return { ok: false, reason: "expired" };
  }

  return { ok: true, key };
}
