import "server-only";
import { createHmac, timingSafeEqual, randomUUID } from "node:crypto";
import { mkdir, writeFile, readFile, unlink } from "node:fs/promises";
import path from "node:path";

/**
 * Private object storage for prescriptions and health records.
 *
 * Non-negotiables, enforced by this module rather than by convention:
 *
 *  - Nothing here ever returns a public URL. The only way to read an object is
 *    a signed, expiring URL minted server-side.
 *  - The storage key is opaque and unguessable (UUID), so knowing a customer's
 *    id tells you nothing about their prescription paths.
 *  - The signature covers the key *and* the expiry, so neither can be edited
 *    without invalidating it.
 *
 * A signed URL is necessary but not sufficient: the route that serves these
 * also re-checks that the caller is entitled to the record. A leaked URL alone
 * must not be enough.
 */

export type StoredObject = {
  body: Buffer;
  contentType: string;
};

export interface PrivateStorage {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

/** Where local development stores objects. Never inside /public. */
const LOCAL_ROOT = path.resolve(process.cwd(), ".private-storage");

class LocalDiskStorage implements PrivateStorage {
  readonly name = "local-disk";

  private resolve(key: string): string {
    // Keys are generated by this module, but a traversal check costs nothing
    // and this is the one place a bad key would escape the sandbox.
    const target = path.resolve(LOCAL_ROOT, key);
    if (!target.startsWith(LOCAL_ROOT + path.sep)) {
      throw new Error("Refusing to resolve a storage key outside the root.");
    }
    return target;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const target = this.resolve(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body);
    await writeFile(`${target}.meta`, contentType, "utf8");
  }

  async get(key: string): Promise<StoredObject | null> {
    try {
      const target = this.resolve(key);
      const [body, contentType] = await Promise.all([
        readFile(target),
        readFile(`${target}.meta`, "utf8").catch(() => "application/octet-stream"),
      ]);
      return { body, contentType };
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      const target = this.resolve(key);
      await unlink(target);
      await unlink(`${target}.meta`).catch(() => {});
    } catch {
      // Already gone.
    }
  }
}

let storage: PrivateStorage | null = null;

export function getStorage(): PrivateStorage {
  if (storage) return storage;

  // S3 is wired in the same way — implement PrivateStorage against the SDK and
  // select it here. The rest of the application does not change.
  if (process.env.S3_BUCKET_PRESCRIPTIONS) {
    throw new Error(
      "S3_BUCKET_PRESCRIPTIONS is set but the S3 driver is not implemented " +
        "yet. Implement PrivateStorage against the S3 SDK and register it in " +
        "getStorage(). Do not fall back to local disk in production.",
    );
  }

  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "No private storage configured. Prescription images are sensitive " +
        "personal data and must not be written to the application filesystem " +
        "in production. Set S3_BUCKET_PRESCRIPTIONS.",
    );
  }

  storage = new LocalDiskStorage();
  return storage;
}

/** Opaque, unguessable key. Prefix is organisational only, never a permission. */
export function newPrescriptionKey(extension: string): string {
  const safeExt = extension.replace(/[^a-z0-9]/gi, "").slice(0, 5) || "bin";
  return `prescriptions/${randomUUID()}.${safeExt}`;
}

export function newHealthRecordKey(extension: string): string {
  const safeExt = extension.replace(/[^a-z0-9]/gi, "").slice(0, 5) || "bin";
  return `health-records/${randomUUID()}.${safeExt}`;
}

function signingSecret(): string {
  const secret = process.env.AUTH_SECRET;
  if (!secret) {
    throw new Error("AUTH_SECRET is required to sign private storage URLs.");
  }
  return secret;
}

function sign(key: string, expiresAt: number): string {
  return createHmac("sha256", signingSecret())
    .update(`${key}:${expiresAt}`)
    .digest("hex");
}

/**
 * Mints a short-lived signed URL.
 *
 * Callers must have already checked that the requester is entitled to the
 * object — this function does not know who is asking.
 */
export function signObjectUrl(key: string, ttlSeconds: number): string {
  const expiresAt = Math.floor(Date.now() / 1000) + ttlSeconds;
  const signature = sign(key, expiresAt);
  const params = new URLSearchParams({
    key,
    exp: String(expiresAt),
    sig: signature,
  });
  return `/api/private-file?${params.toString()}`;
}

export type VerifiedSignature =
  | { ok: true; key: string }
  | { ok: false; reason: "expired" | "invalid" };

export function verifyObjectUrl(
  key: string | null,
  exp: string | null,
  sig: string | null,
): VerifiedSignature {
  if (!key || !exp || !sig) return { ok: false, reason: "invalid" };

  const expiresAt = Number(exp);
  if (!Number.isFinite(expiresAt)) return { ok: false, reason: "invalid" };

  const expected = sign(key, expiresAt);
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(sig, "utf8");
  if (a.length !== b.length || !timingSafeEqual(a, b)) {
    return { ok: false, reason: "invalid" };
  }

  // Expiry is checked after the signature so an attacker cannot use response
  // timing to distinguish a forged signature from a merely stale one.
  if (expiresAt < Math.floor(Date.now() / 1000)) {
    return { ok: false, reason: "expired" };
  }

  return { ok: true, key };
}
