"""baseline: patients, appointments, leads, voice_calls, retention_events, audit_logs

Revision ID: 600c428b0614
Revises: 
Create Date: 2026-09-08 09:25:52.845867
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models define custom column types (GUID, JSONColumn, EncryptedString)
# that autogenerated migrations reference by their module path.
import app.models


revision: str = '600c428b0614'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('patient_uuid', sa.String(length=64), nullable=True),
    sa.Column('subject_hash', sa.String(length=64), nullable=True),
    sa.Column('data_category', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('details', app.models.JSONColumn(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_time', ['action', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_patient_uuid'), ['patient_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_subject_hash'), ['subject_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_patient_time', ['patient_uuid', 'timestamp'], unique=False)

    op.create_table('leads',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('encrypted_phone', app.models.EncryptedString(length=512), nullable=True),
    sa.Column('encrypted_email', app.models.EncryptedString(length=512), nullable=True),
    sa.Column('encrypted_name', app.models.EncryptedString(length=512), nullable=True),
    sa.Column('phone_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('email_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('treatment_interest', sa.String(length=64), nullable=True),
    sa.Column('previous_experience', sa.Boolean(), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=True),
    sa.Column('blood_thinner', sa.Boolean(), nullable=True),
    sa.Column('budget_range', sa.String(length=32), nullable=True),
    sa.Column('timeline', sa.String(length=32), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('next_action', sa.String(length=64), nullable=True),
    sa.Column('needs_provider_approval', sa.Boolean(), nullable=False),
    sa.Column('medical_callback_required', sa.Boolean(), nullable=False),
    sa.Column('calendly_event_id', sa.String(length=120), nullable=True),
    sa.Column('calendly_booking_url', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_state', app.models.JSONColumn(), nullable=False),
    sa.Column('score_breakdown', app.models.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email_fingerprint'), ['email_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone_fingerprint'), ['phone_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_leads_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index('ix_leads_status_created', ['status', 'created_at'], unique=False)

    op.create_table('patients',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('encrypted_name', app.models.EncryptedString(length=512), nullable=True),
    sa.Column('encrypted_phone', app.models.EncryptedString(length=512), nullable=False),
    sa.Column('encrypted_email', app.models.EncryptedString(length=512), nullable=True),
    sa.Column('encrypted_treatment_history', app.models.EncryptedText(), nullable=True),
    sa.Column('encrypted_notes', app.models.EncryptedText(), nullable=True),
    sa.Column('phone_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('email_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('sms_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('preferred_provider', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('last_visit_at', sa.DateTime(), nullable=True),
    sa.Column('reactivation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_email_fingerprint'), ['email_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_external_id'), ['external_id'], unique=False)
        batch_op.create_index('ix_patients_last_visit', ['last_visit_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_last_visit_at'), ['last_visit_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone_fingerprint'), ['phone_fingerprint'], unique=True)

    op.create_table('appointments',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('patient_id', app.models.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('service', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('encrypted_notes', app.models.EncryptedText(), nullable=True),
    sa.Column('reminder_24h_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_2h_sent_at', sa.DateTime(), nullable=True),
    sa.Column('review_requested_at', sa.DateTime(), nullable=True),
    sa.Column('review_received_at', sa.DateTime(), nullable=True),
    sa.Column('reactivation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('credit_offer_sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', app.models.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index('ix_appointments_status_scheduled', ['status', 'scheduled_for'], unique=False)

    op.create_table('retention_events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('patient_id', app.models.GUID(), nullable=True),
    sa.Column('lead_id', app.models.GUID(), nullable=True),
    sa.Column('appointment_id', app.models.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('metadata', app.models.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_events_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_events_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_events_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_retention_type_created', ['event_type', 'created_at'], unique=False)

    op.create_table('voice_calls',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=120), nullable=True),
    sa.Column('patient_id', app.models.GUID(), nullable=True),
    sa.Column('appointment_id', app.models.GUID(), nullable=True),
    sa.Column('transcript', app.models.EncryptedText(), nullable=True),
    sa.Column('encrypted_caller_number', app.models.EncryptedText(), nullable=True),
    sa.Column('caller_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('call_duration', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('ended_reason', sa.String(length=64), nullable=True),
    sa.Column('summary', app.models.JSONColumn(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_calls_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_calls_caller_fingerprint'), ['caller_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_calls_outcome'), ['outcome'], unique=False)
        batch_op.create_index('ix_voice_calls_outcome_created', ['outcome', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_calls_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_calls_vapi_call_id'), ['vapi_call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_calls_vapi_call_id'))
        batch_op.drop_index(batch_op.f('ix_voice_calls_patient_id'))
        batch_op.drop_index('ix_voice_calls_outcome_created')
        batch_op.drop_index(batch_op.f('ix_voice_calls_outcome'))
        batch_op.drop_index(batch_op.f('ix_voice_calls_created_at'))
        batch_op.drop_index(batch_op.f('ix_voice_calls_caller_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_voice_calls_appointment_id'))

    op.drop_table('voice_calls')
    with op.batch_alter_table('retention_events', schema=None) as batch_op:
        batch_op.drop_index('ix_retention_type_created')
        batch_op.drop_index(batch_op.f('ix_retention_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_retention_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_retention_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_retention_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_retention_events_appointment_id'))

    op.drop_table('retention_events')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_external_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_patients_last_visit_at'))
        batch_op.drop_index('ix_patients_last_visit')
        batch_op.drop_index(batch_op.f('ix_patients_external_id'))
        batch_op.drop_index(batch_op.f('ix_patients_email_fingerprint'))

    op.drop_table('patients')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_status_created')
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_source'))
        batch_op.drop_index(batch_op.f('ix_leads_session_id'))
        batch_op.drop_index(batch_op.f('ix_leads_phone_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_leads_email_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))

    op.drop_table('leads')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_patient_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_subject_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_patient_uuid'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_action_time')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
